//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OddsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawledData
    {
        public int Id { get; set; }
        public string PageUrl { get; set; }
        public string FullUrl { get; set; }
        public Nullable<System.DateTime> CrawlDate { get; set; }
        public Nullable<bool> IsLinkCrawled { get; set; }
        public Nullable<bool> IsDataCrawled { get; set; }
        public Nullable<bool> IsInDomain { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public string HtmlContent { get; set; }
    }
}
