//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OddsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlTemplate
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string LayoutControlId { get; set; }
        public string LayoutControlCaption { get; set; }
        public string PlaceholderId { get; set; }
        public string PlaceholderCaption { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
