//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OddsData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFDefault_201712100926Entities : DbContext
    {
        public SFDefault_201712100926Entities()
            : base("name=SFDefault_201712100926Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CrawledData> CrawledDatas { get; set; }
        public DbSet<CrawlDirectory> CrawlDirectories { get; set; }
        public DbSet<CrawlTemplate> CrawlTemplates { get; set; }
    }
}
