CREATE TABLE [dbo].[OAImportConfigurations] (
    [Name]                        NVARCHAR (64)   NOT NULL,
    [DisplayName]                 NVARCHAR (255)  NULL,
    [BaseTypeName]                VARCHAR (255)   NULL,
    [BaseConnectionString]        NVARCHAR (2000) NULL,
    [BaseIsUpdateRequired]        TINYINT         NOT NULL,
    [SourceTypeName]              VARCHAR (255)   NULL,
    [SourceConnectionString]      NVARCHAR (2000) NULL,
    [SourceIsForwardMapped]       TINYINT         NOT NULL,
    [SourceIsUpdateRequired]      TINYINT         NOT NULL,
    [DestinationTypeName]         VARCHAR (255)   NULL,
    [DestinationConectionString]  NVARCHAR (2000) NULL,
    [DestinationIsForwardMapped]  TINYINT         NOT NULL,
    [DestinationIsUpdateRequired] TINYINT         NOT NULL,
    [BaseConfig]                  NVARCHAR (MAX)  NULL,
    [SourceConfig]                NVARCHAR (MAX)  NULL,
    [DestinationConfig]           NVARCHAR (MAX)  NULL,
    [SerializedMapping]           NVARCHAR (MAX)  NULL,
    [ImportType]                  INT             NOT NULL,
    [LogLevel]                    INT             NOT NULL,
    [PageSize]                    INT             NOT NULL,
    [TransactionSize]             INT             NOT NULL,
    [IntermediateCommits]         TINYINT         NOT NULL,
    [CopyToBase]                  TINYINT         NOT NULL,
    [MarkedForDelete]             TINYINT         NULL,
    CONSTRAINT [pk_OAImportConfigurations] PRIMARY KEY CLUSTERED ([Name] ASC)
);

