CREATE TABLE [dbo].[sf_ec_cart_order] (
    [weight]                         FLOAT (53)       NOT NULL,
    [user_id]                        UNIQUEIDENTIFIER NULL,
    [ttal]                           NUMERIC (20, 10) NOT NULL,
    [tax]                            NUMERIC (20, 10) NOT NULL,
    [sub_total_display]              NUMERIC (20, 10) NOT NULL,
    [shipping_total]                 NUMERIC (20, 10) NOT NULL,
    [shipping_tax_rate]              NUMERIC (20, 10) NOT NULL,
    [shipping_tax]                   NUMERIC (20, 10) NOT NULL,
    [shipping_service_name]          NVARCHAR (255)   NULL,
    [shipping_service_code]          NVARCHAR (255)   NULL,
    [shipping_method_id]             UNIQUEIDENTIFIER NULL,
    [shipping_carrier_name]          NVARCHAR (255)   NULL,
    [pre_tax_total]                  NUMERIC (20, 10) NULL,
    [pre_tax_price]                  NUMERIC (20, 10) NOT NULL,
    [pre_discount_tax]               NUMERIC (20, 10) NOT NULL,
    [order_status]                   INT              NOT NULL,
    [order_number]                   INT              NOT NULL,
    [order_date]                     DATETIME         NOT NULL,
    [order_attempts]                 INT              NOT NULL,
    [last_modified]                  DATETIME         NOT NULL,
    [id]                             UNIQUEIDENTIFIER NOT NULL,
    [exchange_rate_total]            NUMERIC (20, 10) NOT NULL,
    [exchange_rate_tax]              NUMERIC (20, 10) NOT NULL,
    [exchnge_rate_sub_total_display] NUMERIC (20, 10) NOT NULL,
    [exchange_rate_sub_total]        NUMERIC (20, 10) NOT NULL,
    [exchange_rate_pre_tax_total]    NUMERIC (20, 10) NOT NULL,
    [exchange_rate_discount_total]   NUMERIC (20, 10) NOT NULL,
    [effective_tax_rate]             NUMERIC (20, 10) NOT NULL,
    [discount_total]                 NUMERIC (20, 10) NOT NULL,
    [currency]                       VARCHAR (255)    NOT NULL,
    [application_name]               VARCHAR (255)    NULL,
    CONSTRAINT [pk_sf_ec_cart_order] PRIMARY KEY CLUSTERED ([id] ASC)
);

