CREATE TABLE [dbo].[sf_libraries] (
    [votes_sum]               NUMERIC (20, 10) NOT NULL,
    [votes_count]             BIGINT           NOT NULL,
    [visible]                 TINYINT          NOT NULL,
    [views_count]             INT              NOT NULL,
    [vrsion]                  INT              NOT NULL,
    [url_name_]               NVARCHAR (255)   NULL,
    [title_]                  NVARCHAR (255)   NULL,
    [status]                  INT              NOT NULL,
    [source_key]              VARCHAR (255)    NULL,
    [publication_date]        DATETIME         NOT NULL,
    [post_rights]             INT              NOT NULL,
    [ownr]                    UNIQUEIDENTIFIER NULL,
    [original_content_id]     UNIQUEIDENTIFIER NULL,
    [last_modified_by]        UNIQUEIDENTIFIER NULL,
    [last_modified]           DATETIME         NULL,
    [include_in_sitemap]      TINYINT          NULL,
    [content_id]              UNIQUEIDENTIFIER NOT NULL,
    [expiration_date]         DATETIME         NULL,
    [email_author]            TINYINT          NULL,
    [draft_culture]           VARCHAR (255)    NULL,
    [description_]            NVARCHAR (255)   NULL,
    [default_page_id]         UNIQUEIDENTIFIER NULL,
    [date_created]            DATETIME         NULL,
    [content_state]           VARCHAR (255)    NULL,
    [approve_comments]        TINYINT          NULL,
    [app_name]                VARCHAR (255)    NULL,
    [allow_track_backs]       TINYINT          NULL,
    [allow_comments]          TINYINT          NULL,
    [running_task]            UNIQUEIDENTIFIER NULL,
    [cache_profile]           VARCHAR (255)    NULL,
    [tmb_regen]               TINYINT          NOT NULL,
    [max_size]                BIGINT           NOT NULL,
    [max_item_size]           BIGINT           NOT NULL,
    [item_default_url_]       NVARCHAR (510)   NULL,
    [is_deleted]              TINYINT          NOT NULL,
    [inherits_permissions]    TINYINT          NOT NULL,
    [security_provider]       VARCHAR (255)    NULL,
    [cover_id]                UNIQUEIDENTIFIER NULL,
    [client_cache_profile]    VARCHAR (255)    NULL,
    [can_inherit_permissions] TINYINT          NOT NULL,
    [blob_storage]            VARCHAR (255)    NULL,
    [voa_class]               INT              NOT NULL,
    [resize_on_upload]        TINYINT          NULL,
    [new_size]                INT              NULL,
    CONSTRAINT [pk_sf_libraries] PRIMARY KEY CLUSTERED ([content_id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idx_sf_libraries]
    ON [dbo].[sf_libraries]([app_name] ASC);

