CREATE TABLE [dbo].[sf_publishing_pipe_settings] (
    [ui_name]                  VARCHAR (255)    NULL,
    [title]                    NVARCHAR (MAX)   NULL,
    [schedule_type]            INT              NOT NULL,
    [schedule_time]            DATETIME         NULL,
    [schedule_day]             INT              NOT NULL,
    [resource_class_id]        VARCHAR (255)    NULL,
    [id3]                      UNIQUEIDENTIFIER NULL,
    [pipe_name]                VARCHAR (255)    NOT NULL,
    [max_items]                INT              NOT NULL,
    [id2]                      UNIQUEIDENTIFIER NULL,
    [last_modified]            DATETIME         NULL,
    [is_inbound]               TINYINT          NOT NULL,
    [is_active]                TINYINT          NOT NULL,
    [invocation_mode]          INT              NOT NULL,
    [id]                       UNIQUEIDENTIFIER NOT NULL,
    [filter_expression]        NVARCHAR (MAX)   NULL,
    [description]              NVARCHAR (255)   NULL,
    [application_name]         VARCHAR (255)    NULL,
    [voa_class]                INT              NOT NULL,
    [voa_version]              SMALLINT         NOT NULL,
    [user_name_reference2]     VARCHAR (255)    NULL,
    [app_id_reference]         INT              NULL,
    [pop3_user_name]           VARCHAR (255)    NULL,
    [pop3_server]              VARCHAR (255)    NULL,
    [pop3_port]                INT              NULL,
    [pop3_password]            VARCHAR (255)    NULL,
    [is_ssl_connection]        TINYINT          NULL,
    [user_name_reference]      VARCHAR (255)    NULL,
    [search_pattern]           VARCHAR (255)    NULL,
    [app_name_reference]       VARCHAR (255)    NULL,
    [url_name]                 NVARCHAR (255)   NULL,
    [output_settings]          INT              NULL,
    [format_settings]          INT              NULL,
    [content_size]             INT              NULL,
    [search_provider_name]     VARCHAR (255)    NULL,
    [catalog_name]             VARCHAR (255)    NULL,
    [provider_name]            VARCHAR (255)    NULL,
    [imported_item_parent_id]  UNIQUEIDENTIFIER NULL,
    [import_item_as_published] TINYINT          NULL,
    [content_type_name]        VARCHAR (255)    NULL,
    [back_links_page_id]       UNIQUEIDENTIFIER NULL,
    CONSTRAINT [pk_sf_publishing_pipe_settings] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idx_sf_pblshng_pp_settings_id3]
    ON [dbo].[sf_publishing_pipe_settings]([id3] ASC);

